Error: Carriage return without line feed received
While altering `Feat` array, we leave out `\r` which raises error because we get -
... 
 ESTA                                                                                                                                                                                
 PASV                                                                                                                                                                                
 EPSV                                                                                                                                                                                
 ESTP
^

instead of

...
 ESTA
 PASV
 EPSV
_____^

Tested on https://ftptest.net (with -P parameter i.e. force_passive_ip) before and after this change.